name: 'Install kevcons'
description: 'Install kevcons CLI tool from source'
inputs:
  go-version:
    description: 'Go version to use'
    required: false
    default: '1.21'
  kevcons-ref:
    description: 'Git ref (branch/tag/commit) to checkout'
    required: false
    default: 'main'
  github-token:
    description: 'GitHub token with repo access for private kevcons repo'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get kevcons commit SHA
      id: kevcons-sha
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        # Debug: verify token is present
        echo "Token length: ${#GH_TOKEN}"

        # Use GitHub CLI to get the commit SHA (it handles auth automatically)
        SHA=$(curl -s -H "Authorization: token ${GH_TOKEN}" \
          "https://api.github.com/repos/kevlarcon/kevcons/commits/${{ inputs.kevcons-ref }}" | \
          jq -r '.sha')

        if [ -z "$SHA" ] || [ "$SHA" = "null" ]; then
          echo "Failed to get SHA for ref ${{ inputs.kevcons-ref }}"
          exit 1
        fi

        echo "sha=$SHA" >> $GITHUB_OUTPUT
        echo "Kevcons ref ${{ inputs.kevcons-ref }} resolves to: $SHA"

    - name: Cache kevcons binary
      id: cache-kevcons
      uses: actions/cache@v4
      with:
        path: /tmp/kevcons-binary
        key: kevcons-${{ runner.os }}-${{ steps.kevcons-sha.outputs.sha }}

    - name: Setup Go
      if: steps.cache-kevcons.outputs.cache-hit != 'true'
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Build kevcons
      if: steps.cache-kevcons.outputs.cache-hit != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        echo "Cache miss - building kevcons from source"
        echo "Ref: ${{ inputs.kevcons-ref }}"
        echo "SHA: ${{ steps.kevcons-sha.outputs.sha }}"

        # Download source as tarball using API (avoids git auth complexity)
        curl -sL -H "Authorization: token ${GH_TOKEN}" \
          "https://api.github.com/repos/kevlarcon/kevcons/tarball/${{ inputs.kevcons-ref }}" \
          -o /tmp/kevcons.tar.gz

        # Extract and find the directory
        mkdir -p /tmp/kevcons-src
        tar -xzf /tmp/kevcons.tar.gz -C /tmp/kevcons-src --strip-components=1

        cd /tmp/kevcons-src

        # Build
        go build -o kevcons

        # Save to cache location
        mkdir -p /tmp/kevcons-binary
        cp kevcons /tmp/kevcons-binary/kevcons

        echo "✓ kevcons built successfully"

    - name: Install kevcons
      shell: bash
      run: |
        if [ "${{ steps.cache-kevcons.outputs.cache-hit }}" = "true" ]; then
          echo "✓ Restored kevcons from cache"
        fi

        # Install from cache location
        sudo cp /tmp/kevcons-binary/kevcons /usr/local/bin/kevcons
        sudo chmod +x /usr/local/bin/kevcons

        # Verify
        kevcons --version
        echo "✓ kevcons installed successfully"
